const styles = {
    container: {
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        background: '#00000091',
        zIndex: 1300,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '20px',
        userSelect: 'none',
    },
    box: {
        width: '480px',
        maxWidth: '100%',
        height: '480px',
        background: '#fff',
        position: 'relative',
        padding: '20px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    closeButton: {
        width: 37,
        height: 48,
        position: 'absolute',
        top: '-5px',
        right: 20,
        outline: 'none',
        border: 'none',
        cursor: 'pointer',
        background: 'url(/img/btnclous.png) no-repeat',
    },
    title: {
        width: '100%',
        fontWeight: 'bold',
        fontSize: 28,
        lineHeight: '160%',
        color: '#464649',
        textAlign: 'center',
        padding: 0,
        margin: 0,
    },
    form: {
        width: '100%',
        margin: 0,
        paddingTop: 25,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
    },
    input: {
        border: '1px solid #dfdfdf',
        background: '#fff',
        outline: 'none',
        padding: '10px',
        fontSize: 16,
        lineHeight: '18px',
        color: '#48484a',
        resize: 'none',
        marginBottom: 15,
    },
    button: {
        width: '100%',
        height: '48px',
        outline: 'none',
        border: 'none',
        cursor: 'pointer',
        color: '#fefefe',
        fontSize: 16,
        lineHeight: '18px',
        background: '#599dbb',
        marginTop: 10,
    },
    error: {
        fontSize: 16,
        lineHeight: '18px',
        color: '#ff0000',
        marginBottom: '10px',
    },
    success: {
        fontSize: 16,
        lineHeight: '18px',
        color: '#14906c',
        marginBottom: '10px',
    },
};

export default styles;